version: '3.3'
services :
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: VMKS
  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - "8010:8080"
